# Generated by Django 5.0.3 on 2024-03-07 15:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('country', models.CharField(max_length=2)),
                ('state', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('q', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=255, null=True)),
                ('screen_width', models.PositiveIntegerField(blank=True, null=True)),
                ('screen_height', models.PositiveIntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=50, null=True)),
                ('user_ip', models.GenericIPAddressField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'search_history',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('dt', models.PositiveIntegerField()),
                ('main_temp', models.FloatField()),
                ('main_feels_like', models.FloatField()),
                ('main_temp_min', models.FloatField()),
                ('main_temp_max', models.FloatField()),
                ('main_pressure', models.IntegerField()),
                ('main_sea_level', models.IntegerField()),
                ('main_grnd_level', models.IntegerField()),
                ('main_humidity', models.IntegerField()),
                ('main_temp_kf', models.FloatField()),
                ('weather_id', models.IntegerField()),
                ('weather_main', models.CharField(max_length=100)),
                ('weather_description', models.CharField(max_length=255)),
                ('weather_icon', models.CharField(max_length=50)),
                ('clouds_all', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('wind_deg', models.IntegerField()),
                ('wind_gust', models.FloatField(blank=True, null=True)),
                ('visibility', models.IntegerField()),
                ('pop', models.FloatField()),
                ('rain_3h', models.FloatField(blank=True, null=True)),
                ('sys_pod', models.CharField(max_length=1)),
                ('dt_txt', models.DateTimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'weather',
            },
        ),
    ]
